### ISSUE TITLE
Structure entities not disappearing after removal

### ISSUE THREAD

**Issue by plytki** [Shynixn/StructureBlockLib#101]
I'm handling the entities and I'm adding them to list and I'm trying to remove them later. I store entities in a list. 
![image](https://user-images.githubusercontent.com/53957038/172245055-221586d2-614f-40a2-99a4-d0e8b25b0ac7.png)
But when I try to remove them they are not removing. 
![image](https://user-images.githubusercontent.com/53957038/172245127-6a67e4bb-feed-46a7-a9e0-1ff6cdf10c7b.png)

What's wrong with that?

**Comment by Shynixn** [comment]
GetEntity does not return the added entity. Instead it is a representation of the stored nbt data using the Entity interface. The actual entities are not accessible at this stage. Just query the chunk/world before and after loading a structure to get the added delta of entities.

**Comment by plytki** [comment]
I don't want to risk like that. Can't I just get the uuids of entities and then get them or add NBT data to the entity and then based on that identify them when getting entities from chunk? I want it to be stable.

**Comment by Shynixn** [comment]
The NMS implementation from mojang removes the UUID tag (and other not known tags) before spawning. There isn't really anything I can do except my previous suggestion because unfortunatly the entity spawning is quite closed. 

Another "more stable" suggestion would be to disable spawning entities, collecting them in a list and spawning them yourself after the structure has been placed.

```
  List<StructureEntity<Entity, Location>> structureEntities = new ArrayList<>();
  List<Entity> entities = new ArrayList<>(); // Final list of the spawned entities you can fully control
  Location targetLocation = ..;
  structureBlockLibApi
          .loadStructure(plugin)
          .at(targetLocation)
          .includeEntities(false)
          .onProcessEntity(structureEntity -> {
              structureEntities.add(structureEntity);
              return false;
          })
          .loadFromPath(..)
          .onResult(e -> {
              for(StructureEntity<Entity, Location> entity : structureEntities){
                  Location entityLocation =  // I am not sure about this calculation. You need to check it yourself.
                          targetLocation.add(entity.getSourceLocation());
                  
                  entity.spawnEntity(entityLocation).ifPresent(addedEntity -> {
                      entities.add(addedEntity);
                  });               
              }
          });


```

**Comment by plytki** [comment]
> The NMS implementation from mojang removes the UUID tag (and other not known tags) before spawning. There isn't really anything I can do except my previous suggestion because unfortunatly the entity spawning is quite closed.
> 
> Another "more stable" suggestion would be to disable spawning entities, collecting them in a list and spawning them yourself after the structure has been placed.
> 
> ```
>   List<StructureEntity<Entity, Location>> structureEntities = new ArrayList<>();
>   List<Entity> entities = new ArrayList<>(); // Final list of the spawned entities you can fully control
>   Location targetLocation = ..;
>   structureBlockLibApi
>           .loadStructure(plugin)
>           .at(targetLocation)
>           .includeEntities(false)
>           .onProcessEntity(structureEntity -> {
>               structureEntities.add(structureEntity);
>               return false;
>           })
>           .loadFromPath(..)
>           .onResult(e -> {
>               for(StructureEntity<Entity, Location> entity : structureEntities){
>                   Location entityLocation =  // I am not sure about this calculation. You need to check it yourself.
>                           targetLocation.clone().add(entity.getSourceLocation());
>                   
>                   entity.spawnEntity(entityLocation).ifPresent(addedEntity -> {
>                       entities.add(addedEntity);
>                   });               
>               }
>           });
> ```

Does not work for me. I can't get entities to spawn.

![image](https://user-images.githubusercontent.com/53957038/172707169-9f8591b2-61ef-42ab-95d6-c8136d8d9335.png)

![image](https://user-images.githubusercontent.com/53957038/172707204-8ddcf764-b7ac-4a66-984f-ef1019ab99a3.png)

**Comment by Shynixn** [comment]
There might be a exception swallowed by the completeable futures. Put a try catch around the code in ``onResult``

**Comment by plytki** [comment]
![image](https://user-images.githubusercontent.com/53957038/172855562-23ff857b-aa35-4b99-8e6a-8d10fe43de44.png)

I got this error, but when I try converting and adding as a vector I get this.

![image](https://user-images.githubusercontent.com/53957038/172855732-3cd911ab-bebf-4c98-8361-d991da0186bd.png)

The proper one is on the left side but the pasted one is the right one.

![image](https://user-images.githubusercontent.com/53957038/172855887-cf970fff-8d6f-40f1-b074-4c27cc84cc17.png)

**Comment by plytki** [comment]
I don't really know how the API works so It's going to be pain in the ass to solve that issue.

**Comment by plytki** [comment]
Also when I will base on my calculations I won't have access to rotation API system which is very important for me.

**Comment by Shynixn** [comment]
for (StructureEntity<Entity, Location> entity : entities) {
                                    entity.getEntity().ifPresent(virtualEntity -> {
                                        Location l = entity.getSourceLocation();
                                        l.add(virtualEntity.getLocation().toVector());
                                        l.setYaw(l.getYaw());
                                        l.setPitch(l.getPitch());
                                        entity.spawnEntity(l);
                                    });
                                }

Did you try it like that?

**Comment by plytki** [comment]
![image](https://user-images.githubusercontent.com/53957038/173096780-5670f592-c555-4ca7-bbf1-3159734c6015.png)
Yes

**Comment by plytki** [comment]
The only way I got it working is this but It's not the nicest way to do that. "/
If there is going be other way to do that please inform me.

` System.out.println("trying to place furniture");
        this.placing = true;
        Set<Entity> beforePasting = new HashSet<>();
        HashMap<Long, Chunk> chunks = new HashMap<>();
        StructureBlockLibApi.INSTANCE
                .loadStructure(plugin)
                .at(targetLocation)
                .includeEntities(true)
                .onProcessEntity(e -> {
                    e.getEntity().ifPresent(entity -> {
                        Location entityLocation = targetLocation.clone().add(e.getSourceLocation().toVector());
                        Chunk chunk = entityLocation.getChunk();
                        if (!chunks.containsKey(chunk.getChunkKey())) {
                            chunks.put(chunk.getChunkKey(), chunk);
                        }
                        Chunk chunk2 = entity.getChunk();
                        if (!chunks.containsKey(chunk2.getChunkKey())) {
                            chunks.put(chunk2.getChunkKey(), chunk2);
                        }
                    });
                    return false;
                })
                .onProcessBlock(e -> false)
                .rotation(rotation)
                .loadFromPath(nbtFile.toPath())
                .onException(e -> plugin.getLogger().log(Level.SEVERE, "Failed to load structure.", e))
                .onResult(e -> {
                    this.usedChunks = new HashMap<>(chunks);
                    chunks.forEach((aLong, chunk) -> {
                        beforePasting.addAll(Arrays.asList(chunk.getEntities()));
                    });
                    StructureBlockLibApi.INSTANCE
                            .loadStructure(plugin)
                            .at(targetLocation)
                            .includeEntities(true)
                            .onProcessEntity(process -> true)
                            .onProcessBlock(process -> false)
                            .rotation(rotation)
                            .loadFromPath(nbtFile.toPath())
                            .onException(process -> plugin.getLogger().log(Level.SEVERE, "Failed to load structure.", process))
                            .onResult(process -> {
                                new BukkitRunnable() {
                                    @Override
                                    public void run() {
                                        Set<Entity> allEntities = new HashSet<>();
                                        usedChunks.forEach((aLong, chunk) -> {
                                            System.out.println("checking chunk: " + aLong);
                                            for (Entity entity : chunk.getEntities()) {
                                                if (!(entity instanceof Player)) {
                                                    allEntities.add(entity);
                                                }
                                            }
                                        });
                                        plugin.getLogger().log(Level.INFO, ChatColor.GREEN + "Loaded structure '" + nbtFile.getName() + "'.");
                                        allEntities.removeAll(beforePasting);
                                        entities = allEntities;
                                        System.out.println(entities.size());
                                        placing = false;
                                    }
                                }.runTaskLater(PartiEffects.getInstance(), 5);
                            });
                });`

**Comment by Shynixn** [comment]
Nice that you got it to work. This behaviour wasn't really the intention of the API (just basic loading/saving structures), so I guess this is the way to do it.

**Comment by plytki** [comment]
I'll paste my final code here in case anyone would need it too.

```
Set<Entity> beforePasting = new HashSet<>();
        StructureBlockLibApi.INSTANCE
                .loadStructure(plugin)
                .at(targetLocation)
                .includeEntities(true)
                .onProcessEntity(e -> {
                    e.getEntity().ifPresent(entity -> {
                        Location entityLocation = targetLocation.clone().add(e.getSourceLocation().toVector());
                        Chunk chunk = entityLocation.getChunk();
                        if (!usedChunks.containsKey(chunk.getChunkKey())) {
                            usedChunks.put(chunk.getChunkKey(), chunk);
                        }
                    });
                    return false;
                })
                .onProcessBlock(e -> false)
                .rotation(rotation)
                .loadFromPath(nbtFile.toPath())
                .onException(e -> plugin.getLogger().log(Level.SEVERE, "Failed to load structure.", e))
                .onResult(e -> {
                    usedChunks.forEach((aLong, chunk) -> {
                        beforePasting.addAll(Arrays.asList(chunk.getEntities()));
                    });
                    StructureBlockLibApi.INSTANCE
                            .loadStructure(plugin)
                            .at(targetLocation)
                            .includeEntities(true)
                            .onProcessEntity(process -> true)
                            .onProcessBlock(process -> false)
                            .rotation(rotation)
                            .loadFromPath(nbtFile.toPath())
                            .onException(process -> plugin.getLogger().log(Level.SEVERE, "Failed to load structure.", process))
                            .onResult(process -> {
                                Set<Entity> allEntities = new HashSet<>();
                                usedChunks.forEach((aLong, chunk) -> {
                                    //System.out.println("checking chunk: " + aLong);
                                    for (Entity entity : chunk.getEntities()) {
                                        if (!(entity instanceof Player)) {
                                            allEntities.add(entity);
                                        }
                                    }
                                });
                                allEntities.removeAll(beforePasting);
                                entities = allEntities;
                                for (Entity entity : entities) {
                                    assignData(entity);
                                }
                                //System.out.println(entities.size());
                                placing = false;
                                plugin.getLogger().log(Level.INFO, "Loaded structure '" + nbtFile.getName() + "'.");
                            });
                });
```
Also you have to block from placing other entities in the chunks that are affected by the structurelib during pasting the structure.
