### ISSUE TITLE
i cannot include StructureBlockLib in my project !

### ISSUE THREAD

**Issue by d3lta-cpp** [Shynixn/StructureBlockLib#104]
IntelliJ report me this Issue when i try to include StructureBlockLib : 
"Dependency 'com.github.shynixn.structureblocklib:structureblocklib-bukkit-api:2.8.0' not found"

**Comment by Shynixn** [comment]
I don't think this is related to this project and depends on your setup in IntelliJ.

**Comment by d3lta-cpp** [comment]
it works fine with gradle
