### ISSUE TITLE
[Suggestion] Visualize Structure.

### ISSUE THREAD

**Issue by ShaneBeee** [Shynixn/StructureBlockLib#34]
Hey, I wanted to make a suggestion, but Im not sure if it's possible.

When using a structure block in game, when you click load, it loads a visualization of how the structure will paste, then when you click load again, it actually pastes it.

I was wondering if that is at all possible to do with this API?

I think it would be super handy to be able to visualize how the structure is going to paste before committing to it. I know I've made the mistake of pasting, and it pastes in the wrong direction or something. Having a visualization would save myself, and I'm sure many others from accidentally pasting in the wrong location.

Thank you for your consideration.

**Comment by Shynixn** [comment]
Hi @ShaneBeee!

Thank you for your suggestion! Hm, actually StructureBlockLib is only a wrapper for the NMS implementation of minecraft and does not perform large abstractions. The internal blocks (blockTypes) are never accessed during the process so it is not possible to access them via the Api. 
Visualizing the process is therefore very difficult to achieve.

**Comment by ShaneBeee** [comment]
So a little while after this, I was playing on my server and I was mistaken, the structure blocks dont visualize the blocks. My bad. They just turn on a wire frame for the player to see the bound where it would be pasted. Would that be possible to do? Perhaps just sending a packet to the player to visualize the bound?

**Comment by Shynixn** [comment]
Unfortunately, this wireframe is completely displayed by the client and cannot be sent via packets.
Don't get me wrong, I like your suggestions but I do not think it is worth including it into this Api. This implementation only adds 1 layer of abstraction to work cross versions but does not do anything else.

**Comment by ShaneBeee** [comment]
> Unfortunately, this wireframe is completely displayed by the client and cannot be sent via packets.
> Don't get me wrong, I like your suggestions but I do not think it is worth including it into this Api. This implementation only adds 1 layer of abstraction to work cross versions but does not do anything else.

Well dang. Thanks for the consideration though, I appreciate it :)
