### ISSUE TITLE
Structure voids not being replaced

### ISSUE THREAD

**Issue by ShaneBeee** [Shynixn/StructureBlockLib#45]
So I noticed when saving/loading structures with this API, structure voids are replacing blocks and pasting as a structure void.
This only happens when saving the structure with this api.

Unless I am missing something, as with the vanilla structures, structure voids should be replaced by the block that is at that location before pasting, Ie: if its air it should be air, if its stone it should be stone. 

Ex: 
creating a structure with a vanilla structure block and loading it with a vanilla structure block:
<img width="966" alt="Screen Shot 2020-08-23 at 2 36 13 PM" src="https://user-images.githubusercontent.com/20008482/90989381-45d4b880-e54e-11ea-97ee-3da6d98551aa.png">
<img width="966" alt="Screen Shot 2020-08-23 at 2 36 35 PM" src="https://user-images.githubusercontent.com/20008482/90989401-6ac92b80-e54e-11ea-86de-f212ea3b0103.png">
Where the grass is in this image, I had a structure void, and it did not replace the grass, as intended.

When saving/loading the same structure via this API:
<img width="966" alt="Screen Shot 2020-08-23 at 2 37 30 PM" src="https://user-images.githubusercontent.com/20008482/90989421-7e749200-e54e-11ea-9ffe-2ed4348dda17.png">
The structure void is pasted

**Comment by Shynixn** [comment]
Hi @ShaneBeee!

Well, the intend of this API is to provide a cross version wrapper for the vanilla structure NMS code. 
So you mean that structures loaded with this API replace non-air-blocks  (non-void-blocks) blocks with stored air-blocks (void-blocks) of the structure file? It might be the case that a flag is not set correctly by the API before executing the load process which is an issue.

**Comment by ShaneBeee** [comment]
What I mean is, a structure void in a structure save, should not replace the blocks where its pasted.

IE: if I have a structure block with a structure void in it, when pasted the void should keep whatever block is currently in the world (see the first 2 pics) 
But when saving with the API, the structure void is not being handled. 

AIR in a structure save should paste as air (as it does properly with this API) the issue is with the structure void block.

**Comment by Shynixn** [comment]
Ah, ok. You mean the https://minecraft.gamepedia.com/Structure_Block#Structure_void block. 
I'll take a look at this.

**Comment by ShaneBeee** [comment]
Yes, took a couple more pics to explain better

I used a structure block to visualize this for ya:
when creating a structure with a structure void in it:
<img width="966" alt="Screen Shot 2020-08-23 at 3 06 34 PM" src="https://user-images.githubusercontent.com/20008482/90989981-7fa7be00-e552-11ea-81a6-07110aa6330d.png">


When loading this structure, the void block should NOT replace the block currently in the world, but its pasting as a structure void:
(hard to see but its there)
<img width="966" alt="Screen Shot 2020-08-23 at 3 07 56 PM" src="https://user-images.githubusercontent.com/20008482/90989992-8fbf9d80-e552-11ea-85d5-f27606fef70e.png">

**Comment by ShaneBeee** [comment]
If I SAVE the structure via a vanilla structure block and LOAD via the API, everything works as intended.

If I SAVE via the API and load via the API or a structure block it does NOT work as intended.

This makes me believe the issue is happening when saving the structure via the API.

**Comment by Shynixn** [comment]
Thank you. It seems like StructureBlockApi uses the old way (1.9) by using Barrier blocks instead of structure voids in all versions. I'll change it to structure voids from 1.10-latest.

**Comment by Shynixn** [comment]
Can you please check if the error has been fixed? 

API:
https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/structureblocklib/structureblocklib-bukkit-api/1.13.0-SNAPSHOT/structureblocklib-bukkit-api-1.13.0-20200824.095612-2.jar
Core:
https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/structureblocklib/structureblocklib-bukkit-core/1.13.0-SNAPSHOT/structureblocklib-bukkit-core-1.13.0-20200824.095625-2.jar

Bukkit-Plugin:
https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/structureblocklib/structureblocklib-bukkit-plugin/1.13.0-SNAPSHOT/structureblocklib-bukkit-plugin-1.13.0-20200824.095634-2.jar

Sample-Plugin:
https://oss.sonatype.org/content/repositories/snapshots/com/github/shynixn/structureblocklib/structureblocklib-bukkit-sample/1.13.0-SNAPSHOT/structureblocklib-bukkit-sample-1.13.0-20200824.095642-2.jar

**Comment by ShaneBeee** [comment]
Sorry for the late response. I had my ringer off (didn't hear email)

Works perfect, thank you so much!!!
