### ISSUE TITLE
Feature Request: please expose structure location logic

### ISSUE THREAD

**Issue by jjaquinta** [Shynixn/StructureBlockLib#49]
*Use case:* I wish to do some post-modification to a structure after it has been rezzed into the world. (resolving jigsaw blocks) I need to understand some specifics of the structure that was just created. (It's dimensions.) For that I need to read the NBT file myself. There is code already in `PersistenceStructureService` that has this information, but it isn't publicly exposed. The workaround for my need is to duplicate the code. But if other developers require this, or the method of locating the physical NBT file from a `StructureSaveConfiguration` changes in the future (e.g. support for structure pools), giving access to the logic would be good.

*Request:* In `PersistenceStructureService`, please expose `boolean structureExists(StructureSaveConfiguration configuration)` as public.
Additionally, refactor the internal logic for finding the files (everything except the .isExists) into another function (say `File getStructureFile(StructureSaveConfiguration configuration)`) and make that public.

**Comment by Shynixn** [comment]
The internal logic is going to be refactored in #47 anyway. 

The structureExists function does not contain any major logic (only version dependent path resolving). You can basically just check if the structure file exists in the world folder.

```
StructureSaveConfiguration configuration;
`boolean exists = new File(configuration.getWorld() + File.separator + "generated" + File.separator + configuration.getAuthor() + File.separator + "structures" + File.separator + configuration.getSaveName() + ".nbt").exists()
```

**Comment by Shynixn** [comment]
Changed in #47.
