### ISSUE TITLE
Version 2.2.2 Not Compatible with 1.16.1 (and possibly other versions)

### ISSUE THREAD

**Issue by MrPeterss** [Shynixn/StructureBlockLib#85]
Title - I keep getting a cannot find class error... fixed it by using version 2.0.0

**Comment by Shynixn** [comment]
Yes, this behaviour is intended. Sub versions like 1.16.0-1.16.2 are no longer supported in the latest StructureBlockLib versions. Only the latest version of a major build is, like: 1.16.3-1.16.5.
